#!/bin/bash

npm init -y

npm install express mongoose express-session body-parser ejs express-flash

mkdir client client/static client/views server server/routes server/controllers server/models

touch server/controllers/controller.js server/server.js
touch client/views/index.ejs server/routes/route.js 
touch .gitignore

cat <<'EOF' > ./client/views/index.ejs
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
  <h1>Hello World!</h1>
</body>
</html>
EOF

cat <<'EOF' > ./server/server.js
const express = require('express')
const app = express()
const bodyParser = require('body-parser')
const mongoose = require('mongoose')
const session = require('express-session')
const path = require('path')

const MONGODB_URI = 'mongodb://localhost/#*#*#*#*#*#'
mongoose.connect(MONGODB_URI)
app.use(bodyParser.urlencoded({ extended: true}))
app.use(bodyParser.json());
app.use(session({
  secret: 'keyboardkitteh',
  resave: false,
  saveUninitialized: true,
  cookie: { maxAge: 60000}
}))


app.use(express.static(path.join(__dirname, '../public/dist/public/')));

require('./routes/route')(app)

app.listen(8000, ()=> console.log('listening on port 8000'))
EOF

cat <<'EOF' > ./.gitignore
/node_modules
package-lock.json
EOF

cat <<'EOF' > ./server/routes/route.js
const controller = require("../controllers/controller")
module.exports = (app) => {
  
}
EOF

cat <<'EOF' > ./server/controllers/controller.js
module.exports = {
  index: function(req, res){
    res.render('index')
  }
}
EOF

echo Do you want a github repo? 
read ans
if [ "$ans" = "y" ] || [ "$ans" == "Y" ]
then
echo what is your github link?
read github
git init 
git remote add origin $github
fi

ng new public

(cd public && ng build --watch)